- name: fix root .bashrc
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: copy over /etc/skel files to /root
      command: cp -a /etc/skel/. /root/
      args:
        creates: /root/.bashrc

- name: etcd
  hosts: all
  gather_facts: false
  become: true
  roles:
    - etcd
  tags:
    - etcd

- name: flannel
  hosts: all
  gather_facts: false
  become: true
  roles:
    - flannel
  tags:
    - flannel

- name: openshift-cli
  hosts: all
  gather_facts: false
  become: true
  roles:
    - openshift-cli
  tags:
    - openshift-cli

- name: openshift-master servers
  hosts: openshift-master
  gather_facts: false
  become: true
  roles:
    - openshift-master
  tags:
    - openshift-master

- name: openshift-node servers
  hosts: openshift-node
  gather_facts: false
  become: true
  roles:
    - openshift-node
  tags:
    - openshift-node

- name: openshift manage cluster
  hosts: openshift-master[0]
  gather_facts: false
  become: true
  roles:
    - openshift-manage-cluster
  tags:
    - openshift-manage-cluster

- name: openshift registry
  hosts: openshift-master[0]
  gather_facts: false
  become: true
  roles:
    - openshift-registry
  tags:
    - openshift-registry

- name: openshift router
  hosts: openshift-master[0]
  gather_facts: false
  become: true
  roles:
    - openshift-router
  tags:
    - openshift-router
